version: '3.8'

services:
  
  app:
    image: mymeals-app:${APP_VERSION:-2.0.0}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-pos-app
    ports:
      - "3002:8080"
    volumes:
      - ./sqlite.db:/app/sqlite.db
    restart: always
    environment:
      - NODE_ENV=production
